// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blobs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "List Blob Storage Items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/blobs.SuccessResponse-array_blobs_Blob"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/blobs.FailureResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new Storage Blob",
                "parameters": [
                    {
                        "description": "Details of the blob",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/blobs.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Blob is created successfully",
                        "schema": {
                            "$ref": "#/definitions/blobs.SuccessResponse-blobs_Blob"
                        }
                    },
                    "400": {
                        "description": "There was an error creating the blob",
                        "schema": {
                            "$ref": "#/definitions/blobs.FailureResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "blobs.Blob": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version_id": {
                    "type": "string"
                }
            }
        },
        "blobs.CreateRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "blobs.FailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "blobs.SuccessResponse-array_blobs_Blob": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/blobs.Blob"
                    }
                }
            }
        },
        "blobs.SuccessResponse-blobs_Blob": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/blobs.Blob"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Simple Blob Storage Consumer API",
	Description:      "A simple implementation example for Azure blob storage",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
