definitions:
  blobs.Blob:
    properties:
      name:
        type: string
      version_id:
        type: string
    type: object
  blobs.CreateRequest:
    properties:
      content:
        type: string
      name:
        type: string
    type: object
  blobs.FailureResponse:
    properties:
      error:
        type: string
    type: object
  blobs.SuccessResponse-array_blobs_Blob:
    properties:
      data:
        items:
          $ref: '#/definitions/blobs.Blob'
        type: array
    type: object
  blobs.SuccessResponse-blobs_Blob:
    properties:
      data:
        $ref: '#/definitions/blobs.Blob'
    type: object
info:
  contact: {}
  description: A simple implementation example for Azure blob storage
  title: Simple Blob Storage Consumer API
paths:
  /blobs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blobs.SuccessResponse-array_blobs_Blob'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/blobs.FailureResponse'
      summary: List Blob Storage Items
    post:
      consumes:
      - application/json
      parameters:
      - description: Details of the blob
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/blobs.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Blob is created successfully
          schema:
            $ref: '#/definitions/blobs.SuccessResponse-blobs_Blob'
        "400":
          description: There was an error creating the blob
          schema:
            $ref: '#/definitions/blobs.FailureResponse'
      summary: Create a new Storage Blob
swagger: "2.0"
